<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: circle-arrow-up (outline) */
export const ArrowTopCircle_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: [
    'M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0',
    'M12 8l-4 4',
    'M12 8v8',
    'M16 12l-4 -4',
  ],
})
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {ArrowTopCircle_Stroke2_Corner0_Rounded as CanonicalArrowTopCircle_Stroke2_Corner0_Rounded} from './Arrow'

/** @deprecated Import ArrowTopCircle_Stroke2_Corner0_Rounded from `#/components/icons/Arrow` instead. */
export const ArrowTopCircle_Stroke2_Corner0_Rounded =
  CanonicalArrowTopCircle_Stroke2_Corner0_Rounded
>>>>>>> upstream/main
