<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: arrow-down-from-arc (outline) */
export const ArrowOutOfBox_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: ['M12 15v-12', 'M16 7l-4 -4l-4 4', 'M3 12a9 9 0 0 0 18 0'],
})

/** Tabler: arrow-down-from-arc (outline) */
export const ArrowOutOfBoxModified_Stroke2_Corner2_Rounded = createTablerIcon({
  paths: ['M12 15v-12', 'M16 7l-4 -4l-4 4', 'M3 12a9 9 0 0 0 18 0'],
})
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {ArrowOutOfBox_Stroke2_Corner0_Rounded as CanonicalArrowOutOfBox_Stroke2_Corner0_Rounded} from './Arrow'
import {ArrowOutOfBoxModified_Stroke2_Corner2_Rounded as CanonicalArrowOutOfBoxModified_Stroke2_Corner2_Rounded} from './Arrow'

/** @deprecated Import ArrowOutOfBox_Stroke2_Corner0_Rounded from `#/components/icons/Arrow` instead. */
export const ArrowOutOfBox_Stroke2_Corner0_Rounded =
  CanonicalArrowOutOfBox_Stroke2_Corner0_Rounded

/** @deprecated Import ArrowOutOfBoxModified_Stroke2_Corner2_Rounded from `#/components/icons/Arrow` instead. */
export const ArrowOutOfBoxModified_Stroke2_Corner2_Rounded =
  CanonicalArrowOutOfBoxModified_Stroke2_Corner2_Rounded
>>>>>>> upstream/main
