<<<<<<< HEAD:src/components/icons/Bars.tsx
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: menu-2 (outline) */
export const Bars3_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: ['M4 6l16 0', 'M4 12l16 0', 'M4 18l16 0'],
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {createSinglePathSVG} from './TEMPLATE'

export const Bars3_Stroke2_Corner0_Rounded = createSinglePathSVG({
  path: 'M3 5a1 1 0 0 0 0 2h18a1 1 0 1 0 0-2H3Zm-1 7a1 1 0 0 1 1-1h18a1 1 0 1 1 0 2H3a1 1 0 0 1-1-1Zm0 6a1 1 0 0 1 1-1h18a1 1 0 1 1 0 2H3a1 1 0 0 1-1-1Z',
  viewBox: '0 0 24 24',
>>>>>>> upstream/main:src/components/icons/Bars3.tsx
})
