<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: ban (outline) */
export const CircleBanSign_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: ['M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0', 'M5.7 5.7l12.6 12.6'],
})
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {CircleBanSign_Stroke2_Corner0_Rounded as CanonicalCircleBanSign_Stroke2_Corner0_Rounded} from './Circle'

/** @deprecated Import CircleBanSign_Stroke2_Corner0_Rounded from `#/components/icons/Circle` instead. */
export const CircleBanSign_Stroke2_Corner0_Rounded =
  CanonicalCircleBanSign_Stroke2_Corner0_Rounded
>>>>>>> upstream/main
