<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: info-circle (outline) */
export const CircleInfo_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: ['M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0', 'M12 9h.01', 'M11 12h1v4h1'],
})
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {CircleInfo_Stroke2_Corner0_Rounded as CanonicalCircleInfo_Stroke2_Corner0_Rounded} from './Circle'

/** @deprecated Import CircleInfo_Stroke2_Corner0_Rounded from `#/components/icons/Circle` instead. */
export const CircleInfo_Stroke2_Corner0_Rounded =
  CanonicalCircleInfo_Stroke2_Corner0_Rounded
>>>>>>> upstream/main
