<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: circle-plus (outline) */
export const CirclePlus_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: ['M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0', 'M9 12h6', 'M12 9v6'],
})
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {CirclePlus_Stroke2_Corner0_Rounded as CanonicalCirclePlus_Stroke2_Corner0_Rounded} from './Circle'

/** @deprecated Import CirclePlus_Stroke2_Corner0_Rounded from `#/components/icons/Circle` instead. */
export const CirclePlus_Stroke2_Corner0_Rounded =
  CanonicalCirclePlus_Stroke2_Corner0_Rounded
>>>>>>> upstream/main
