<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: circle-square (outline) */
export const Circle_And_Square_Stroke1_Corner0_Rounded_Filled =
  createTablerIcon({
    paths: [
      'M3 9.5a6.5 6.5 0 1 0 13 0a6.5 6.5 0 1 0 -13 0',
      'M10 12a2 2 0 0 1 2 -2h7a2 2 0 0 1 2 2v7a2 2 0 0 1 -2 2h-7a2 2 0 0 1 -2 -2l0 -7',
    ],
  })
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {CircleAndSquare_Stroke1_Corner0_Rounded_Filled as CanonicalCircle_And_Square_Stroke1_Corner0_Rounded_Filled} from './Circle'

/** @deprecated Import CircleAndSquare_Stroke1_Corner0_Rounded_Filled from `#/components/icons/Circle` instead. */
export const Circle_And_Square_Stroke1_Corner0_Rounded_Filled =
  CanonicalCircle_And_Square_Stroke1_Corner0_Rounded_Filled
>>>>>>> upstream/main
