<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: clipboard (outline) */
export const Clipboard_Stroke2_Corner2_Rounded = createTablerIcon({
  paths: [
    'M9 5h-2a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-12a2 2 0 0 0 -2 -2h-2',
    'M9 5a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2',
  ],
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {createSinglePathSVG} from './TEMPLATE'

export const Clipboard_Stroke2_Corner2_Rounded = createSinglePathSVG({
  path: 'M8.17 4A3 3 0 0 1 11 2h2c1.306 0 2.418.835 2.83 2H17a3 3 0 0 1 3 3v12a3 3 0 0 1-3 3H7a3 3 0 0 1-3-3V7a3 3 0 0 1 3-3h1.17ZM8 6H7a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V7a1 1 0 0 0-1-1h-1v1a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1V6Zm6 0V5a1 1 0 0 0-1-1h-2a1 1 0 0 0-1 1v1h4Z',
  viewBox: '0 0 24 24',
>>>>>>> upstream/main
})
