<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: brackets (outline) */
export const CodeBrackets_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: ['M8 4h-3v16h3', 'M16 4h3v16h-3'],
})

/** Tabler: brackets (outline) */
export const CodeBrackets_Stroke2_Corner2_Rounded = createTablerIcon({
  paths: ['M8 4h-3v16h3', 'M16 4h3v16h-3'],
})
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {CodeBrackets_Stroke2_Corner0_Rounded as CanonicalCodeBrackets_Stroke2_Corner0_Rounded} from './Code'
import {CodeBrackets_Stroke2_Corner2_Rounded as CanonicalCodeBrackets_Stroke2_Corner2_Rounded} from './Code'

/** @deprecated Import CodeBrackets_Stroke2_Corner0_Rounded from `#/components/icons/Code` instead. */
export const CodeBrackets_Stroke2_Corner0_Rounded =
  CanonicalCodeBrackets_Stroke2_Corner0_Rounded

/** @deprecated Import CodeBrackets_Stroke2_Corner2_Rounded from `#/components/icons/Code` instead. */
export const CodeBrackets_Stroke2_Corner2_Rounded =
  CanonicalCodeBrackets_Stroke2_Corner2_Rounded
>>>>>>> upstream/main
