<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: source-code (outline) */
export const CodeLines_Stroke2_Corner2_Rounded = createTablerIcon({
  paths: [
    'M14.5 4h2.5a3 3 0 0 1 3 3v10a3 3 0 0 1 -3 3h-10a3 3 0 0 1 -3 -3v-5',
    'M6 5l-2 2l2 2',
    'M10 9l2 -2l-2 -2',
  ],
})
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {CodeLines_Stroke2_Corner2_Rounded as CanonicalCodeLines_Stroke2_Corner2_Rounded} from './Code'

/** @deprecated Import CodeLines_Stroke2_Corner2_Rounded from `#/components/icons/Code` instead. */
export const CodeLines_Stroke2_Corner2_Rounded =
  CanonicalCodeLines_Stroke2_Corner2_Rounded
>>>>>>> upstream/main
