<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: filter-2-down (outline) */
export const FilterTimeline_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: [
    'M4 6h16',
    'M6 12h12',
    'M9 18h3',
    'M19 16v6',
    'M19 22l3 -3',
    'M19 22l-3 -3',
  ],
})
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {FilterTimeline_Stroke2_Corner0_Rounded as CanonicalFilterTimeline_Stroke2_Corner0_Rounded} from './Filter'

/** @deprecated Import FilterTimeline_Stroke2_Corner0_Rounded from `#/components/icons/Filter` instead. */
export const FilterTimeline_Stroke2_Corner0_Rounded =
  CanonicalFilterTimeline_Stroke2_Corner0_Rounded
>>>>>>> upstream/main
