<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: globe (outline) */
export const Globe_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: [
    'M7 9a4 4 0 1 0 8 0a4 4 0 0 0 -8 0',
    'M5.75 15a8.015 8.015 0 1 0 9.25 -13',
    'M11 17v4',
    'M7 21h8',
  ],
})

/** Tabler: world (outline) */
export const Earth_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: [
    'M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0',
    'M3.6 9h16.8',
    'M3.6 15h16.8',
    'M11.5 3a17 17 0 0 0 0 18',
    'M12.5 3a17 17 0 0 1 0 18',
  ],
})

/** Tabler: world (outline) */
export const Earth_Stroke2_Corner2_Rounded = createTablerIcon({
  paths: [
    'M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0',
    'M3.6 9h16.8',
    'M3.6 15h16.8',
    'M11.5 3a17 17 0 0 0 0 18',
    'M12.5 3a17 17 0 0 1 0 18',
  ],
})
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {Earth_Stroke2_Corner0_Rounded as CanonicalEarth_Stroke2_Corner0_Rounded} from './Earth'
import {Earth_Stroke2_Corner2_Rounded as CanonicalEarth_Stroke2_Corner2_Rounded} from './Earth'
import {createSinglePathSVG} from './TEMPLATE'

export const Globe_Stroke2_Corner0_Rounded = createSinglePathSVG({
  path: 'M4.062 11h2.961c.103-2.204.545-4.218 1.235-5.77a9 9 0 0 1 .188-.399A8 8 0 0 0 4.062 11ZM12 2C6.477 2 2 6.477 2 12s4.477 10 10 10 10-4.477 10-10S17.523 2 12 2Zm0 2c-.227 0-.518.1-.868.432-.354.337-.719.872-1.047 1.61-.561 1.263-.958 2.991-1.06 4.958h5.95c-.102-1.967-.499-3.695-1.06-4.958-.328-.738-.693-1.273-1.047-1.61C12.518 4.099 12.227 4 12 4Zm4.977 7c-.103-2.204-.545-4.218-1.235-5.77a10 10 0 0 0-.188-.399A8 8 0 0 1 19.938 11h-2.961Zm-2.003 2H9.026c.101 1.966.498 3.695 1.06 4.958.327.738.692 1.273 1.046 1.61.35.333.641.432.868.432s.518-.1.868-.432c.354-.337.719-.872 1.047-1.61.561-1.263.958-2.991 1.06-4.958Zm.58 6.169a9 9 0 0 0 .188-.399c.69-1.552 1.132-3.566 1.235-5.77h2.961a8 8 0 0 1-4.384 6.169Zm-7.108 0a10 10 0 0 1-.188-.399c-.69-1.552-1.132-3.566-1.235-5.77H4.062a8 8 0 0 0 4.384 6.169Z',
  viewBox: '0 0 24 24',
})

/** @deprecated Import Earth_Stroke2_Corner0_Rounded from `#/components/icons/Earth` instead. */
export const Earth_Stroke2_Corner0_Rounded =
  CanonicalEarth_Stroke2_Corner0_Rounded

/** @deprecated Import Earth_Stroke2_Corner2_Rounded from `#/components/icons/Earth` instead. */
export const Earth_Stroke2_Corner2_Rounded =
  CanonicalEarth_Stroke2_Corner2_Rounded
>>>>>>> upstream/main
