<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: growth (outline) */
export const Growth_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: [
    'M16.5 15a4.5 4.5 0 0 0 -4.5 4.5m4.5 -8.5a4.5 4.5 0 0 0 -4.5 4.5m4.5 -8.5a4.5 4.5 0 0 0 -4.5 4.5m-4 3.5c2.21 0 4 2.015 4 4.5m-4 -8.5c2.21 0 4 2.015 4 4.5m-4 -8.5c2.21 0 4 2.015 4 4.5m0 -7.5v6',
  ],
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {createSinglePathSVG} from './TEMPLATE'

export const Growth_Stroke2_Corner0_Rounded = createSinglePathSVG({
  path: 'M3 4a1 1 0 0 1 1-1h1a8 8 0 0 1 7.75 6.006A7.99 7.99 0 0 1 19 6h1a1 1 0 0 1 1 1v1a8 8 0 0 1-8 8v4a1 1 0 1 1-2 0v-7a8 8 0 0 1-8-8V4Zm2 1a6 6 0 0 1 6 6 6 6 0 0 1-6-6Zm8 9a6 6 0 0 1 6-6 6 6 0 0 1-6 6Z',
  viewBox: '0 0 24 24',
>>>>>>> upstream/main
})
