<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {
  createTablerFilledIcon,
  createTablerIcon,
} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: heart (outline) */
export const Heart2_Stroke1_Corner0_Rounded = createTablerIcon({
  paths: [
    'M19.5 12.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572',
  ],
  strokeWidth: 1.25,
})

/** Tabler: heart (outline) */
export const Heart2_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: [
    'M19.5 12.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572',
  ],
})

/** Tabler: heart (filled) */
export const Heart2_Filled_Stroke2_Corner0_Rounded = createTablerFilledIcon({
  paths: [
    'M6.979 3.074a6 6 0 0 1 4.988 1.425l.037 .033l.034 -.03a6 6 0 0 1 4.733 -1.44l.246 .036a6 6 0 0 1 3.364 10.008l-.18 .185l-.048 .041l-7.45 7.379a1 1 0 0 1 -1.313 .082l-.094 -.082l-7.493 -7.422a6 6 0 0 1 3.176 -10.215z',
  ],
})

/** Tabler: heart (outline) */
export const LikeRepost_Stroke2_Corner2_Rounded = createTablerIcon({
  paths: [
    'M19.5 12.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572',
  ],
})
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {LikeRepost_Stroke2_Corner2_Rounded as CanonicalLikeRepost_Stroke2_Corner2_Rounded} from './LikeRepost'
import {createSinglePathSVG} from './TEMPLATE'

export const Heart2_Filled_Stroke2_Corner0_Rounded = createSinglePathSVG({
  path: 'M12.489 21.372c8.528-4.78 10.626-10.47 9.022-14.47-.779-1.941-2.414-3.333-4.342-3.763-1.697-.378-3.552.003-5.169 1.287-1.617-1.284-3.472-1.665-5.17-1.287-1.927.43-3.562 1.822-4.34 3.764-1.605 4 .493 9.69 9.021 14.47a1 1 0 0 0 .978 0Z',
  viewBox: '0 0 24 24',
})

export const Heart2_Stroke1_Corner0_Rounded = createSinglePathSVG({
  path: 'M49 17c0 15.333-22 26.667-24 26.667S1 32.333 1 17C1 6.333 7.667 1 14.333 1S25 5 25 5s4-4 10.667-4S49 6.333 49 17Z',
  viewBox: '0 0 50 45',
  strokeWidth: 2,
  strokeLinejoin: 'round',
})

export const Heart2_Stroke2_Corner0_Rounded = createSinglePathSVG({
  path: 'M16.734 5.091c-1.238-.276-2.708.047-4.022 1.38a1 1 0 0 1-1.424 0C9.974 5.137 8.504 4.814 7.266 5.09c-1.263.282-2.379 1.206-2.92 2.556C3.33 10.18 4.252 14.84 12 19.348c7.747-4.508 8.67-9.168 7.654-11.7-.541-1.351-1.657-2.275-2.92-2.557Zm4.777 1.812c1.604 4-.494 9.69-9.022 14.47a1 1 0 0 1-.978 0C2.983 16.592.885 10.902 2.49 6.902c.779-1.942 2.414-3.334 4.342-3.764 1.697-.378 3.552.003 5.169 1.286 1.617-1.283 3.472-1.664 5.17-1.286 1.927.43 3.562 1.822 4.34 3.764Z',
  viewBox: '0 0 24 24',
})

/** @deprecated Import LikeRepost_Stroke2_Corner2_Rounded from `#/components/icons/LikeRepost` instead. */
export const LikeRepost_Stroke2_Corner2_Rounded =
  CanonicalLikeRepost_Stroke2_Corner2_Rounded
>>>>>>> upstream/main
