<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: list-search (outline) */
export const ListMagnifyingGlass_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: [
    'M11 15a4 4 0 1 0 8 0a4 4 0 1 0 -8 0',
    'M18.5 18.5l2.5 2.5',
    'M4 6h16',
    'M4 12h4',
    'M4 18h4',
  ],
})
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {ListMagnifyingGlass_Stroke2_Corner0_Rounded as CanonicalListMagnifyingGlass_Stroke2_Corner0_Rounded} from './List'

/** @deprecated Import ListMagnifyingGlass_Stroke2_Corner0_Rounded from `#/components/icons/List` instead. */
export const ListMagnifyingGlass_Stroke2_Corner0_Rounded =
  CanonicalListMagnifyingGlass_Stroke2_Corner0_Rounded
>>>>>>> upstream/main
