<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: loader (outline) */
export const Loader_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: [
    'M12 6l0 -3',
    'M16.25 7.75l2.15 -2.15',
    'M18 12l3 0',
    'M16.25 16.25l2.15 2.15',
    'M12 18l0 3',
    'M7.75 16.25l-2.15 2.15',
    'M6 12l-3 0',
    'M7.75 7.75l-2.15 -2.15',
  ],
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {createSinglePathSVG} from './TEMPLATE'

export const Loader_Stroke2_Corner0_Rounded = createSinglePathSVG({
  path: 'M12 5a7 7 0 0 0-5.218 11.666A1 1 0 0 1 5.292 18a9 9 0 1 1 13.416 0 1 1 0 1 1-1.49-1.334A7 7 0 0 0 12 5Z',
  viewBox: '0 0 24 24',
>>>>>>> upstream/main
})
