<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: file-x (outline) */
export const PageX_Stroke2_Corner0_Rounded_Large = createTablerIcon({
  paths: [
    'M14 3v4a1 1 0 0 0 1 1h4',
    'M17 21h-10a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2h7l5 5v11a2 2 0 0 1 -2 2',
    'M10 12l4 4m0 -4l-4 4',
  ],
})
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {PageX_Stroke2_Corner0_Rounded_Large as CanonicalPageX_Stroke2_Corner0_Rounded_Large} from './Page'

/** @deprecated Import PageX_Stroke2_Corner0_Rounded_Large from `#/components/icons/Page` instead. */
export const PageX_Stroke2_Corner0_Rounded_Large =
  CanonicalPageX_Stroke2_Corner0_Rounded_Large
>>>>>>> upstream/main
