<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: volume (outline) */
export const SpeakerVolumeFull_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: [
    'M15 8a5 5 0 0 1 0 8',
    'M17.7 5a9 9 0 0 1 0 14',
    'M6 15h-2a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1h2l3.5 -4.5a.8 .8 0 0 1 1.5 .5v14a.8 .8 0 0 1 -1.5 .5l-3.5 -4.5',
  ],
})
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {SpeakerVolumeFull_Stroke2_Corner0_Rounded as CanonicalSpeakerVolumeFull_Stroke2_Corner0_Rounded} from './SpeakerVolumeFull'

/** @deprecated Import SpeakerVolumeFull_Stroke2_Corner0_Rounded from `#/components/icons/SpeakerVolumeFull` instead. */
export const SpeakerVolumeFull_Stroke2_Corner0_Rounded =
  CanonicalSpeakerVolumeFull_Stroke2_Corner0_Rounded
>>>>>>> upstream/main
