<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: copy (outline) */
export const SquareBehindSquare4_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: [
    'M7 9.667a2.667 2.667 0 0 1 2.667 -2.667h8.666a2.667 2.667 0 0 1 2.667 2.667v8.666a2.667 2.667 0 0 1 -2.667 2.667h-8.666a2.667 2.667 0 0 1 -2.667 -2.667l0 -8.666',
    'M4.012 16.737a2.005 2.005 0 0 1 -1.012 -1.737v-10c0 -1.1 .9 -2 2 -2h10c.75 0 1.158 .385 1.5 1',
  ],
})

/** Tabler: copy (outline) */
export const SquareBehindSquare_Stroke2_Corner2_Rounded = createTablerIcon({
  paths: [
    'M7 9.667a2.667 2.667 0 0 1 2.667 -2.667h8.666a2.667 2.667 0 0 1 2.667 2.667v8.666a2.667 2.667 0 0 1 -2.667 2.667h-8.666a2.667 2.667 0 0 1 -2.667 -2.667l0 -8.666',
    'M4.012 16.737a2.005 2.005 0 0 1 -1.012 -1.737v-10c0 -1.1 .9 -2 2 -2h10c.75 0 1.158 .385 1.5 1',
  ],
})
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {SquareBehindSquare_Stroke2_Corner2_Rounded as CanonicalSquareBehindSquare_Stroke2_Corner2_Rounded} from './Square'
import {SquareBehindSquare4_Stroke2_Corner0_Rounded as CanonicalSquareBehindSquare4_Stroke2_Corner0_Rounded} from './Square'

/** @deprecated Import SquareBehindSquare_Stroke2_Corner2_Rounded from `#/components/icons/Square` instead. */
export const SquareBehindSquare_Stroke2_Corner2_Rounded =
  CanonicalSquareBehindSquare_Stroke2_Corner2_Rounded

/** @deprecated Import SquareBehindSquare4_Stroke2_Corner0_Rounded from `#/components/icons/Square` instead. */
export const SquareBehindSquare4_Stroke2_Corner0_Rounded =
  CanonicalSquareBehindSquare4_Stroke2_Corner0_Rounded
>>>>>>> upstream/main
