<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: swipe (outline) */
export const StarterPackMultiPathLarge = createTablerIcon({
  paths: [
    'M15 16.572v2.42a2.01 2.01 0 0 1 -2.009 2.008h-7.981a2.01 2.01 0 0 1 -2.01 -2.009v-7.981a2.01 2.01 0 0 1 2.009 -2.01h2.954',
    'M9.167 4.511a2.04 2.04 0 0 1 2.496 -1.441l7.826 2.097a2.04 2.04 0 0 1 1.441 2.496l-2.097 7.826a2.04 2.04 0 0 1 -2.496 1.441l-7.827 -2.097a2.04 2.04 0 0 1 -1.441 -2.496l2.098 -7.827l0 .001',
  ],
})

/** Tabler: swipe (outline) */
export const StarterPack_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: [
    'M15 16.572v2.42a2.01 2.01 0 0 1 -2.009 2.008h-7.981a2.01 2.01 0 0 1 -2.01 -2.009v-7.981a2.01 2.01 0 0 1 2.009 -2.01h2.954',
    'M9.167 4.511a2.04 2.04 0 0 1 2.496 -1.441l7.826 2.097a2.04 2.04 0 0 1 1.441 2.496l-2.097 7.826a2.04 2.04 0 0 1 -2.496 1.441l-7.827 -2.097a2.04 2.04 0 0 1 -1.441 -2.496l2.098 -7.827l0 .001',
  ],
})
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {StarterPack_Stroke2_Corner0_Rounded as CanonicalStarterPack_Stroke2_Corner0_Rounded} from './brands/StarterPack'
import {StarterPackMultiPathLarge as CanonicalStarterPackMultiPathLarge} from './brands/StarterPack'

/** @deprecated Import StarterPack_Stroke2_Corner0_Rounded from `#/components/icons/brands/StarterPack` instead. */
export const StarterPack_Stroke2_Corner0_Rounded =
  CanonicalStarterPack_Stroke2_Corner0_Rounded

/** @deprecated Import StarterPackMultiPathLarge from `#/components/icons/brands/StarterPack` instead. */
export const StarterPackMultiPathLarge = CanonicalStarterPackMultiPathLarge
>>>>>>> upstream/main
