<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: text-size (outline) */
export const TextSize_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: [
    'M3 7v-2h13v2',
    'M10 5v14',
    'M12 19h-4',
    'M15 13v-1h6v1',
    'M18 12v7',
    'M17 19h2',
  ],
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {createSinglePathSVG} from './TEMPLATE'

export const TextSize_Stroke2_Corner0_Rounded = createSinglePathSVG({
  path: 'M9 5a1 1 0 0 1 1-1h12a1 1 0 1 1 0 2h-5v14a1 1 0 1 1-2 0V6h-5a1 1 0 0 1-1-1Zm-3.073 7v8a1 1 0 1 0 2 0v-8H12a1 1 0 1 0 0-2H2a1 1 0 1 0 0 2h3.927Z',
  viewBox: '0 0 24 24',
>>>>>>> upstream/main
})
