<<<<<<< HEAD
/**
 * Generated from Tabler icons. Do not edit by hand.
 *
 * Regenerate with scripts/generate-tabler-icons.mjs.
 */
// northsky: upstream glyphs replaced with Tabler icons
import {createTablerIcon} from '#/features/tablerIcons/createTablerIcon'

/** Tabler: x (outline) */
export const TimesLarge_Stroke2_Corner0_Rounded = createTablerIcon({
  paths: ['M18 6l-12 12', 'M6 6l12 12'],
})
=======
// This file is generated by pnpm icons:generate. Do not edit.

import {TimesLarge_Stroke2_Corner0_Rounded as CanonicalTimesLarge_Stroke2_Corner0_Rounded} from './TimesLarge'

/** @deprecated Import TimesLarge_Stroke2_Corner0_Rounded from `#/components/icons/TimesLarge` instead. */
export const TimesLarge_Stroke2_Corner0_Rounded =
  CanonicalTimesLarge_Stroke2_Corner0_Rounded
>>>>>>> upstream/main
